stop_commands = ["stop", "exit", "quit", "sleep"]

sites = [["YouTube", "https://youtube.com"], ["Google", "https://www.google.com"],
         ["Facebook", "https://www.facebook.com"], ["Instagram", "https://www.instagram.com"],
         ["Twitter", "https://www.twitter.com"], ["Amazon", "https://www.amazon.com"],
         ["WhatsApp", "https://www.whatsapp.com"], ["Play Store", "https://play.google.com"],
         ["Wikipedia", "https://www.wikipedia.org"], ["Quora", "https://www.quora.com"],
         ["Netflix", "https://www.netflix.com"], ["Spotify", "https://www.spotify.com"],
         ["Gmail","https://gmail.com/"],
         ["Chatgpt", "https://chat.openai.com/?next=%2Fchat"],
         ["Gemini", "https://gemini.google.com/app"],
         ["Clude", "https://claude.ai/chats"],
         ["Mistral", "https://chat.mistral.ai/chat"],
         ["Amazon", "https://www.amazon.com/"],
         ["Flipkart", "https://www.flipkart.com/"],
         ["Mintra", "https://www.myntra.com/"]]

apps = [["Notepad", "notepad.exe"],
        ["Calculator", "calc.exe"],
        ["Command Prompt", "cmd.exe"],
        ["Windows Explorer", "explorer.exe"],
        ["Task Manager", "taskmgr.exe"],
        ["Microsoft Edge", "msedge.exe"],
        ["Google Chrome", "chrome.exe"],
        ["Mozilla Firefox", "firefox.exe"],
        ["Paint", "mspaint.exe"],
        ["WordPad", "wordpad.exe"],
        ["Microsoft Word", "winword.exe"],
        ["Microsoft Excel", "excel.exe"],
        ["Microsoft PowerPoint", "powerpnt.exe"],
        ["Microsoft Outlook", "outlook.exe"],
        ["Windows Media Player", "wmplayer.exe"],
        ["VLC Media Player", "vlc.exe"],
        ["Windows Defender", "msmpsvc.exe"],
        ["Windows Security", "wscui.cpl"],
        ["Control Panel", "control.exe"],
        ["Settings", "ms-settings:"],
        ["Windows Update", "wuapp.exe"],
        ["Snipping Tool", "snippingtool.exe"],
        ["Remote Desktop Connection", "mstsc.exe"],
        ["Microsoft Teams", "teams.exe"],
        ["Zoom", "zoom.exe"],
        ["Skype", "skype.exe"],
        ["Discord", "discord.exe"],
        ["Steam", "steam.exe"],
        ["Spotify", "spotify.exe"],
        ["Photoshop", "photoshop.exe"],
        ["Illustrator", "illustrator.exe"],
        ["InDesign", "indesign.exe"],
        ["Visual Studio Code", "code.exe"],
        ["Sublime Text", "sublime_text.exe"],
        ["Notepad++", "notepad++.exe"],
        ["PuTTY", "putty.exe"],
        ["WinRAR", "winrar.exe"],
        ["7-Zip", "7zFM.exe"],
        ["VirtualBox", "virtualbox.exe"]]


songs = [["Dil hai mushkil", "https://youtu.be/6FURuLYrR_Q?si=kkSJFDoutMNPaNEu"],
         ["Nusrat fateh ali khan qauwalli", "https://youtu.be/FIzjqBtb_xo?si=-EOjxGdcld2H6Vkl"],
         ["Yar na miley", "https://youtu.be/2520y5ad1GQ?si=SdiSYz73b_adXCop"],
         ["Sawan me", "https://youtu.be/uFsV0ieoU-w?si=eDKvyjKZ79c8-ZJA"]]
